# fly.toml app configuration file generated for ticker-change on 2026-07-27T03:22:19-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'ticker-change'
primary_region = 'sjc'

[build]

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1

[env]
  DB_PATH = '/data/stocks.db'
  MODEL_PATH = '/data/model.pkl'
  PORT = '8000'

[[mounts]]
  source = 'stocks_data'
  destination = '/data'
